from fastapi import APIRouter, status

from ..db import pool
from ..models import DrugCreate, DrugUpdate

router = APIRouter(prefix="/drugs", tags=["drugs"])


@router.post("", status_code=status.HTTP_201_CREATED)
def create_drug(d: DrugCreate):
    with pool.connection() as conn:
        conn.execute(
            "CALL insert_drug(%s, %s, %s)", [d.trade_name, d.formula, d.company_name]
        )
        # drug_id is auto-generated by the identity column; read it back (visible
        # inside this same transaction) so the client gets the new id.
        cur = conn.execute(
            "SELECT drug_id FROM drug WHERE trade_name = %s AND company_name = %s",
            [d.trade_name, d.company_name],
        )
        row = cur.fetchone()
    return {
        "message": "drug created",
        "drug_id": row["drug_id"],
        "trade_name": d.trade_name,
        "company_name": d.company_name,
    }


@router.put("/{drug_id}")
def update_drug(drug_id: int, body: DrugUpdate):
    with pool.connection() as conn:
        conn.execute("CALL update_drug_formula(%s, %s)", [drug_id, body.formula])
    return {"message": "drug updated", "drug_id": drug_id}


@router.delete("/{drug_id}")
def delete_drug(drug_id: int):
    with pool.connection() as conn:
        conn.execute("CALL delete_drug(%s)", [drug_id])
    return {"message": "drug deleted", "drug_id": drug_id}
